# Node.js version
environment:
  martix:
    # node.js
    #- nodejs_version: "6" WTF?

# install scripts (runs after repo cloning)
install:
  # get the latest Node.js or io.js
  - ps: Install-Product node 6
  # install modules
  - npm install

# post install
test_script:
  # output info
  - node --version
  - npm --version
  # run tests
  - npm test

# don't actually build
build: off
